package flights_management_system;
import static flights_management_system.Search_Flight_Details.username;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSetMetaData;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shoba
 */
public class Mybookings extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst,pst1;
    ResultSet rs,rs1;
    static String username;
    public  Mybookings(String username) {
        initComponents();
        conn=javaconnect.ConnectDb();
        this.username=username;
        fetch(username);
    }
    
public void fetch(String username) {
    try {
        String sql = "SELECT * FROM book_ticket WHERE C_Name = ?";
        String sql1 = "SELECT * FROM cancel_ticket WHERE C_Name = ?";
        
        pst = conn.prepareStatement(sql);
        pst1 = conn.prepareStatement(sql1);
        
        pst.setString(1, username);
        pst1.setString(1, username);
        
        ResultSet rs1 = pst.executeQuery();
        ResultSet rs2 = pst1.executeQuery();
        
        // Merge the result sets into a single result set
        ResultSetMetaData rs1Meta = rs1.getMetaData();
        ResultSetMetaData rs2Meta = rs2.getMetaData();
        int columnCount = rs1Meta.getColumnCount();
        
        DefaultTableModel model = new DefaultTableModel();
        
        // Add column names to the table model
        for (int i = 1; i <= columnCount; i++) {
            model.addColumn(rs1Meta.getColumnName(i));
        }
        
        // Add rows from the first result set
        while (rs1.next()) {
            Object[] rowData = new Object[columnCount];
            for (int i = 1; i <= columnCount; i++) {
                rowData[i - 1] = rs1.getObject(i);
            }
            model.addRow(rowData);
        }
        
        // Add rows from the second result set
        while (rs2.next()) {
            Object[] rowData = new Object[columnCount];
            for (int i = 1; i <= columnCount; i++) {
                rowData[i - 1] = rs2.getObject(i);
            }
            model.addRow(rowData);
        }
        
        // Set the combined result set to the jtable model
        jtable.setModel(model);
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}

//
//public void fetch(String username) {
//    try {
//        String sql ="SELECT * FROM book_ticket WHERE C_Name = ?";
//        String sql1="select *from cancel_ticket where C_Name=?";
//        pst = conn.prepareStatement(sql);
//        pst1 = conn.prepareStatement(sql1);
//        pst.setString(1, username);
//        pst1.setString(1,username);
//        rs = pst.executeQuery();
//        rs1=pst1.executeQuery();
//        jtable.setModel(DbUtils.resultSetToTableModel(rs));
//        jtable.setModel(DbUtils.resultSetToTableModel(rs1));
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BOOKING HISTORY");

        jtable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ticket_no", "Flight_No", "FlightName", "source", "Destination", "Date", "Arrival_Time", "Departure_Time", "Total_Price", "Seats", "Customer Name", "Status"
            }
        ));
        jScrollPane1.setViewportView(jtable);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(653, 653, 653))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton1)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        userdashboard ob=new userdashboard(username);
        ob.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mybookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mybookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mybookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mybookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mybookings(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable;
    // End of variables declaration//GEN-END:variables
}
